"""baseline schema

The four tables that api/models.py already defined when Alembic was introduced:
meetings, agent_configs, personalizations, organization_plans. Autogenerated
against an empty database, then verified by re-running --autogenerate (which
produced no further changes) and by a full upgrade/downgrade cycle.

An existing deployment created by Base.metadata.create_all should be stamped
rather than upgraded, so this baseline is not re-applied over live tables:

    alembic stamp head

Revision ID: 8059008c9497
Revises: 
Create Date: 2026-08-19 22:28:57.582433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8059008c9497'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('org', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=200), nullable=False),
    sa.Column('agent_secret', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('gemini_api_key', sa.String(length=200), nullable=True),
    sa.Column('org_client_id', sa.String(length=200), nullable=True),
    sa.Column('org_client_secret', sa.String(length=500), nullable=True),
    sa.Column('custom_prompt', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('org')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('time_zone', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('actor_user_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_org'), ['org'], unique=False)

    op.create_table('organization_plans',
    sa.Column('org', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('org')
    )
    op.create_table('personalizations',
    sa.Column('org', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_alt_text', sa.String(length=200), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('org')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personalizations')
    op.drop_table('organization_plans')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_org'))

    op.drop_table('meetings')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###
